config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  post 'stringify', to: 'pages#stringify'
  get 'age', to: 'pages#person'
  put 'age', to: 'pages#person'
  get 'me', to: 'me#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/foobar.rb
class Foobar
  # ENTER CODE FOR Q2 HERE
  def initialize(value)
    @passedValue = value
  end

  def bar(value1, value2)
    return "#{value1}#{@passedValue}#{value2[:sat]}"
  end
end

app/controllers/concerns/person.rb
class Person
  attr_accessor :nickname, :name, :age

  def initialize(name, age)
    @name = name
    @age = age
    @nickname = name[0..3]
  end

  def introduce
    return "#{@name}, #{@age} years old."
  end

  def birth_year
    return Date.today.prev_year(age).year
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    foo = Foobar.new "baz"
    @baz = foo.bar :cat, sat: :dat, dat: :sat
  end

  def stringify
    if params[:name].blank? && params[:adjective].blank?
      @text  = 'You are Nothing!'
    else
      @text = "#{params[:name]} is #{params[:adjective]}"
    end
  end

  def age
  end

  def person
    @person = Person.new(params[:name], params[:age].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/me/index.html.erb
<p>This is me ~..~</p>
<p>A new born coder.</p>
<h1>Find me on <a href="https://github.com/Kate9202">github</a></h1>

app/views/pages/age.html.erb
<h1>REROUTE ME!</h1>

app/views/pages/home.html.erb
<h1>Hello There! Welcome to homework 2!</h1>
<p>What a beautiful homepage!</p>
<p>Good thing this isn't the web design decal.</p>

<h1>Question 1</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag stringify_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name %>
  <%= label_tag :adjective, "An adjective here!" %>
  <%= text_area_tag :adjective %>
  <%= submit_tag "Stringify!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<h1>Question 2</h1>

<p>Your result</p>
<%= @baz %>

<h1>Question 3</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag age_path, method: :put do %>
  <%= label_tag :name, "Your name:" %>
  <%= text_area_tag :name %>
  <%= label_tag :age, "Your age:" %>
  <%= text_area_tag :age %>
  <%= submit_tag "Submit!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

app/views/pages/person.html.erb
<h3>Introduction: <%= @person.introduce %></h3>
<h4>Birth Year: <%= @person.birth_year %></h4>
<h4>Nickname: <%= @person.nickname %></h4>

app/views/pages/stringify.html.erb
<p><%= @text %></p>